# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data01', '0010_auto_20171123_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedbackpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basepost', models.CharField(default='Add Feedback here', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pd2',
            name='addway',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pd2',
            name='gift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pd2',
            name='addurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data01.feedbackpost'),
        ),
    ]
